### PR TITLE
Release 0.0.1

### PR DESCRIPTION
**Pull request by michalstolarczyk**

### CODE REVIEW

**Comment by michalstolarczyk** [comment]
I think you might be looking at the `master` branch. Your concerns are addressed in `dev`.

**Comment by nsheff** [comment]
Ok, one suggestion: in the vignette, demonstrate 2 ways to build a BP object: 1. function (you already have); 2. provide existing data. does that make sense?

**Comment by nsheff** [comment]
also, did the lambda function idea not work?

**Comment by michalstolarczyk** [comment]
> also, did the lambda function idea not work?

I realized that it would involve some `initialize` method redesign, whereas the current approach was the matter of changing a line of code. And it works just fine.
If you think the benefits of lambda outweigh that we can still change it

**Pull request merged**
